"""change_dni_length_to_8

Revision ID: 15a4f381e3c7
Revises: 13f93869d906
Create Date: 2025-03-04 19:19:52.385873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a4f381e3c7'
down_revision: Union[str, None] = '13f93869d906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dni',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dni',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
