"""minor2

Revision ID: abc213959a3d
Revises: 1a615a352224
Create Date: 2025-01-03 18:28:10.839976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc213959a3d'
down_revision: Union[str, None] = '1a615a352224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###
